root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server/"
  bin = "./tmp/main"
  delay = 1000
  include_ext = ["go", "html", "css", "js"]
  exclude_dir = ["tmp", "bin", "old_python", "mysql", ".git", "node_modules"]
  exclude_regex = ["_test\\.go"]

[log]
  time = true

[misc]
  clean_on_exit = true
